name: Update Balloon Data and Deploy

on:
  schedule:
    # Runs at 03:00 UTC every day (adjust as needed)
    # Use https://crontab.guru/ to help define cron schedules
    - cron: '0 3 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessary to commit changes back to the repo

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Or specify your exact version, e.g., '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests # Add any other Python dependencies your script needs

      - name: Run Python Script to Update Data
        env:
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        run: python your_python_script.py # Make sure this is the correct name of your script

      - name: Commit and Push Updated Data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add windborne_data_with_weather.json # Or the exact name of your output JSON file
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "Automated daily data update"
            git push
            echo "Data updated and pushed."
          fi
